### ISSUE TITLE
"connect ECONNREFUSED 127.0.0.1:443" in Node.js Lambda

### ISSUE THREAD

**Issue by kovalev-org** [stackimpact/stackimpact-nodejs#2]
I followed the instructions from the blog post: https://stackimpact.com/blog/aws-lambda-cpu-and-memory-profiling-node-js/. But it seems that something's wrong with the agent:

> StackImpact 1.1.4: Error uploading messages to the dashboard, backing off next upload
> StackImpact 1.1.4: connect ECONNREFUSED 127.0.0.1:443
> StackImpact 1.1.4: Error: connect ECONNREFUSED 127.0.0.1:443 at Object.exports._errnoException (util.js:1018:11) at exports._exceptionWithHostPort (util.js:1041:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

I'm not sure how it is supposed to work. I use Serverless to build Lambdas on my local Macbook, so `npm install stackimpact` would yield:

```
> node node-gyp-fallback.js

Pre-built version of StackImpact addon not found, trying to build.
  CXX(target) Release/obj.target/stackimpact-addon/src/stackimpact_addon.o
  CXX(target) Release/obj.target/stackimpact-addon/src/heap_stats.o
  CXX(target) Release/obj.target/stackimpact-addon/src/gc_stats.o
  CXX(target) Release/obj.target/stackimpact-addon/src/event_loop_stats.o
  CXX(target) Release/obj.target/stackimpact-addon/src/cpu_profiler.o
  CXX(target) Release/obj.target/stackimpact-addon/src/allocation_sampler.o
  SOLINK_MODULE(target) Release/stackimpact-addon.node
npm WARN layered-loss@1.0.0 No repository field.

+ stackimpact@1.1.4
added 2 packages in 5.074s
```

Then `serverless deploy` would package everything including `./node_modules/` and upload it to AWS. But how an executable that was built against OS X will run on Amazon Linux?

**Comment by kovalev-org** [comment]
> But how an executable that was built against OS X will run on Amazon Linux?

That's not the issue. Deploying from Amazon Linux machine leads to the same result:

> StackImpact 1.1.4: Using pre-built native addon.
> StackImpact 1.1.4: Agent started
> ...
> StackImpact 1.1.4: ApiRequest: config request took 396ms
> StackImpact 1.1.4: { hostname: 'agent-api.stackimpact.com',
port: null,
method: 'POST',
path: '/agent/v1/config',
headers: 
{ Host: 'agent-api.stackimpact.com',
'Content-Type': 'application/json',
'Content-Encoding': 'gzip',
'Accept-Encoding': 'gzip',
Authorization: 'Basic XXXXXXX=' } }
> ...
> StackImpact 1.1.4: Agent deactivated.
> ...
> StackImpact 1.1.4: Using pre-built native addon.
> ...
> StackImpact 1.1.4: connect ECONNREFUSED 127.0.0.1:443

I'm worried about that **Agent deactivated** part.

**Comment by kovalev-org** [comment]
I figured it out. You have to do `stackimpact.start(...)` outside your handler. For some reason you can't create a new agent per every call (makes sence, why would you do that?) or maybe have to destroy agent at the end of a call.
