### ISSUE TITLE
Unable to install on Azure server

### ISSUE THREAD

**Issue by soutarm** [stackimpact/stackimpact-nodejs#4]
Similar to Issue #1 I am unable to install the package on either of my Azure Web Apps (Windows based running Kudu). It all works fine locally on my Windows 10 laptop but NPM install fails on the servers (output below. full log is attached)

I've tried upgrading to Node 10.6 (latest version Azure supports), then downgrading back to Node 8.11.1. I double checked that the machines are running in 64bit.

```
...
89 verbose stack Error: stackimpact@1.3.10 install: `node node-gyp-fallback.js`
89 verbose stack Exit status 1
89 verbose stack     at EventEmitter.<anonymous> (D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
89 verbose stack     at EventEmitter.emit (events.js:182:13)
89 verbose stack     at ChildProcess.<anonymous> (D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
89 verbose stack     at ChildProcess.emit (events.js:182:13)
89 verbose stack     at maybeClose (internal/child_process.js:961:16)
89 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
90 verbose pkgid stackimpact@1.3.10
91 verbose cwd D:\home\site\wwwroot
92 verbose Windows_NT 10.0.14393
93 verbose argv "D:\\Program Files (x86)\\nodejs\\10.6.0\\node.exe" "D:\\Program Files (x86)\\npm\\6.1.0\\node_modules\\npm\\bin\\npm-cli.js" "install" "stackimpact"
94 verbose node v10.6.0
95 verbose npm  v6.1.0
96 error code ELIFECYCLE
97 error errno 1
98 error stackimpact@1.3.10 install: `node node-gyp-fallback.js`
98 error Exit status 1
99 error Failed at the stackimpact@1.3.10 install script.
99 error This is probably not a problem with npm. There is likely additional logging output above.
100 verbose exit [ 1, true ]
```

Any help would be greatly appreciated as I'd really like to use this service.
[2018-11-26T02_02_17_579Z-debug.log](https://github.com/stackimpact/stackimpact-nodejs/files/2613865/2018-11-26T02_02_17_579Z-debug.log)

**Comment by soutarm** [comment]
According to Azure support their Web Apps only run x86 Node (there is a manual way to override) while this package only runs on 64 bit systems.
